/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author Charly Cimino
 */
public class Screen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Screen.class.getName());

    /**
     * Creates new form Screen
     */
    public Screen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel1 = new javax.swing.JPanel();
        escritorio = new javax.swing.JDesktopPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_Alumno = new javax.swing.JMenu();
        jmi_agregarAlumno = new javax.swing.JMenuItem();
        jm_Materia = new javax.swing.JMenu();
        jmi_agregarMateria = new javax.swing.JMenuItem();
        jm_Registro = new javax.swing.JMenu();
        jmi_Inscripcion = new javax.swing.JMenuItem();
        jm_Salir = new javax.swing.JMenu();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        jm_Alumno.setText("Alumno");

        jmi_agregarAlumno.setText("Agregar alumno");
        jm_Alumno.add(jmi_agregarAlumno);

        jMenuBar1.add(jm_Alumno);

        jm_Materia.setText("Materia");

        jmi_agregarMateria.setText("Agregar materia");
        jm_Materia.add(jmi_agregarMateria);

        jMenuBar1.add(jm_Materia);

        jm_Registro.setText("Registro");

        jmi_Inscripcion.setText("Inscribir alumno");
        jmi_Inscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_InscripcionActionPerformed(evt);
            }
        });
        jm_Registro.add(jmi_Inscripcion);

        jMenuBar1.add(jm_Registro);

        jm_Salir.setText("Salir");
        jm_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_SalirActionPerformed(evt);
            }
        });
        jm_Salir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jm_SalirKeyPressed(evt);
            }
        });
        jMenuBar1.add(jm_Salir);

        jInternalFrame1.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 711, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );

        escritorio.setLayer(jInternalFrame1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jm_SalirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jm_SalirKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jm_SalirKeyPressed

    private void jm_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_SalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jm_SalirActionPerformed

    private void jmi_InscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_InscripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_InscripcionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JMenu jm_Alumno;
    private javax.swing.JMenu jm_Materia;
    private javax.swing.JMenu jm_Registro;
    private javax.swing.JMenu jm_Salir;
    private javax.swing.JMenuItem jmi_Inscripcion;
    private javax.swing.JMenuItem jmi_agregarAlumno;
    private javax.swing.JMenuItem jmi_agregarMateria;
    // End of variables declaration//GEN-END:variables
}
