/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;
import java.util.HashSet;
import tp4laboratorio.Materia;
/**
 *
 * @author Charly Cimino
 */
public class VistaMateria extends javax.swing.JInternalFrame {
    private final HashSet<Materia> materias;
    /**
     * Creates new form VistaMateria
     */
    public VistaMateria(HashSet <Materia> materias) {
        initComponents();
        this.materias=materias;
    }
    
    private void limpiarCampos (){
        txt_Codigo.setText("");
        txt_NombreMateria.setText("");
        txt_AnioMateria.setText("");
        
        txt_Codigo.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_Codigo = new javax.swing.JTextField();
        txt_NombreMateria = new javax.swing.JTextField();
        txt_AnioMateria = new javax.swing.JTextField();
        guardarMateria = new javax.swing.JButton();
        nuevoMateria = new javax.swing.JButton();
        salirMateria = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setText("Formulario de Materias");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel2.setText("Codigo");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel4.setText("Año");

        guardarMateria.setText("Guardar");
        guardarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarMateriaActionPerformed(evt);
            }
        });

        nuevoMateria.setText("Nuevo");
        nuevoMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoMateriaActionPerformed(evt);
            }
        });

        salirMateria.setText("Salir");
        salirMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirMateriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(guardarMateria))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_NombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_AnioMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(nuevoMateria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(salirMateria)))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txt_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_NombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_AnioMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarMateria)
                    .addComponent(nuevoMateria)
                    .addComponent(salirMateria))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoMateriaActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_nuevoMateriaActionPerformed

    private void salirMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirMateriaActionPerformed
        dispose();
    }//GEN-LAST:event_salirMateriaActionPerformed

    private void guardarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarMateriaActionPerformed
        if (txt_Codigo.getText().isBlank() || txt_NombreMateria.getText().isBlank() || txt_AnioMateria.getText().isBlank()) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Completá los campos"
        );

        return;
    }

    try {

        int codigo = Integer.parseInt(txt_Codigo.getText());
        String nombre = txt_NombreMateria.getText();
        int anio = Integer.parseInt(txt_AnioMateria.getText());

        Materia materia = new Materia(codigo, nombre, anio);

        boolean agregada = materias.add(materia);

        if (agregada) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Materia guardada correctamente"
            );

            limpiarCampos();

        } else {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "La materia ya existe"
            );
        }

    } catch (NumberFormatException e) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Código y año deben ser números"
        );
    }
        
    }//GEN-LAST:event_guardarMateriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton guardarMateria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton nuevoMateria;
    private javax.swing.JButton salirMateria;
    private javax.swing.JTextField txt_AnioMateria;
    private javax.swing.JTextField txt_Codigo;
    private javax.swing.JTextField txt_NombreMateria;
    // End of variables declaration//GEN-END:variables
}
