/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;
import java.util.HashSet;
import tp4laboratorio.Alumno;
import tp4laboratorio.Materia;
import java.util.ArrayList;

/**
 *
 * @author Charly Cimino
 */
public class VistaInscripcion extends javax.swing.JInternalFrame {
    private final HashSet<Alumno> alumnos;
    private final HashSet <Materia> materias;
    
    private final ArrayList<Alumno> listaAlumnos = new ArrayList<>();
    private final ArrayList<Materia> listaMaterias = new ArrayList<>();
    /**
     * Creates new form VistaInscripcion
     */
    public VistaInscripcion(HashSet <Alumno> alumnos, HashSet <Materia> materias) {
        initComponents();
        this.alumnos=alumnos;
        this.materias=materias;
        cargarCombos();
        
    }
    
    private void cargarCombos() {

    opcion_Alumno.removeAllItems();
    opcion_Materia.removeAllItems();

    listaAlumnos.clear();
    listaMaterias.clear();

    listaAlumnos.addAll(alumnos);
    listaMaterias.addAll(materias);

    for (Alumno alumno : listaAlumnos) {
        opcion_Alumno.addItem(
                alumno.getLegajo()
                + " - "
                + alumno.getApellido()
                + " "
                + alumno.getNombre()
        );
    }

    for (Materia materia : listaMaterias) {
        opcion_Materia.addItem(
                materia.getIdMateria()
                + " - "
                + materia.getNombre()
        );
    }

    opcion_Alumno.setSelectedIndex(-1);
    opcion_Materia.setSelectedIndex(-1);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        opcion_Materia = new javax.swing.JComboBox<>();
        opcion_Alumno = new javax.swing.JComboBox<>();
        btn_Inscribir = new javax.swing.JButton();
        salirInscribir = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setText("Formulario de Inscripcion");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel2.setText("Elija una materia");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel3.setText("Elija un alumno");

        opcion_Materia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        opcion_Alumno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_Inscribir.setText("Inscribir");
        btn_Inscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InscribirActionPerformed(evt);
            }
        });

        salirInscribir.setText("Salir");
        salirInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirInscribirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(opcion_Alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(43, 43, 43)
                            .addComponent(opcion_Materia, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(btn_Inscribir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salirInscribir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(opcion_Materia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(opcion_Alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Inscribir)
                    .addComponent(salirInscribir))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_InscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InscribirActionPerformed
        int posicionAlumno = opcion_Alumno.getSelectedIndex();
    int posicionMateria = opcion_Materia.getSelectedIndex();

    if (posicionAlumno == -1 || posicionMateria == -1) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Debe seleccionar un alumno y una materia"
        );

        return;
    }

    Alumno alumnoSeleccionado =
            listaAlumnos.get(posicionAlumno);

    Materia materiaSeleccionada =
            listaMaterias.get(posicionMateria);

    int cantidadAnterior =
            alumnoSeleccionado.cantidadMaterias();

    alumnoSeleccionado.agregarMateria(
            materiaSeleccionada
    );

    int cantidadActual =
            alumnoSeleccionado.cantidadMaterias();

    if (cantidadActual > cantidadAnterior) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Inscripción realizada correctamente.\n"
                + "Alumno: "
                + alumnoSeleccionado.getApellido()
                + " "
                + alumnoSeleccionado.getNombre()
                + "\nMateria: "
                + materiaSeleccionada.getNombre()
                + "\nCantidad de materias: "
                + cantidadActual
        );
    } else {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "El alumno ya está inscripto en esa materia"
        );
    }
    }//GEN-LAST:event_btn_InscribirActionPerformed

    private void salirInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirInscribirActionPerformed
        dispose();
    }//GEN-LAST:event_salirInscribirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Inscribir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> opcion_Alumno;
    private javax.swing.JComboBox<String> opcion_Materia;
    private javax.swing.JButton salirInscribir;
    // End of variables declaration//GEN-END:variables
}
